### ISSUE TITLE
peer2peer code review

### ISSUE THREAD

**Issue by Odongo006** [Yemisirach/Leader-board-#4]
Hello Yemi, you're so close to completing this one, I think your project would look more complete if you address the issues below: -

- Kindly deploy the last version of your project.

**Comment by Yemisirach** [comment]
Hello Yemi, you're so close to completing this one, I think your project would look more complete if you address the issues below: -

- Kindly deploy the last version of your project.

Thank you for you suggestion. I will fix 👍  .

**Comment by Yemisirach** [comment]
I fix it. Thank you
